### ISSUE TITLE
"display:-webkit-box;" causes issue in newer version of Safari

### ISSUE THREAD

**Issue by kristianwithak** [kristoferjoseph/flexboxgrid#141]
From what I can gather, this set of rules present on `.row`:

```
display:-webkit-flex;
display:-ms-flexbox;
display:-webkit-box;
display:flex;
```

...causes issues in newer version of safari. Here's the details...

I'm viewing a site using flexbox grid in Safari 9.

Because safari ignores the `display:flex;` rule, it falls back to `display:-webkit-box`. But, since that rule is specific to older versions of safari, it does nothing.

Yet, even though it does nothing, the browser doesn't continue to fall back to the `display:-webkit-flex` declaration... so the elements with class `.row` remain "unflexed".

I suspect the fix is to simply re-order the rules like so...

```
display:-webkit-box;
display:-webkit-flex;
display:-ms-flexbox;
display:flex;
```

**Comment by sumobi** [comment]
Similar issue but related. I found that Safari 9 works fine, but Safari 8 has a broken layout. 

On Safari 8, a simple row layout is broken. Code:

    <section class="container-fluid">

            <div class="row">

                <div class="col-xs-12 col-lg-8" style="background:red">
                    test
                </div>

                <div class="col-xs-12 col-lg-4" style="background:blue">
                    test
                </div>

            </div>
        </section>

Result for Safari 8:

<img width="1395" alt="wdcxkszbev-3000x3000" src="https://cloud.githubusercontent.com/assets/52581/11461618/a5cd60f6-976b-11e5-81cd-6c9d6082e43d.png">

Moving `display:-webkit-flex;` below `display:-webkit-box;` fixes the issue:

<img width="1500" alt="ug-368r2sf-3000x3000" src="https://cloud.githubusercontent.com/assets/52581/11461623/b887a300-976b-11e5-86c8-7cddeded23ad.png">

Test still works in Safari 9.

**Comment by bkrall** [comment]
@sumobi's fix looks promising, but still having this issue in Safari 9.

Anything else to try (pretty new to Flexbox)?

**Comment by kristoferjoseph** [comment]
This is an order issue with `autoprefixer` it will be fixed in a new version.

**Comment by bkrall** [comment]
@kristoferjoseph thanks for the reply, do you know what the correct order is? Planning on just fixing this manually.

**Comment by kristianwithak** [comment]
I believe the order should be...

```
display:-webkit-box;
display:-webkit-flex;
display:-ms-flexbox;
display:flex;
```

**Comment by JSeligsohn** [comment]
+ 1 Having same issue on Safari 9.0.2

**Comment by maus86** [comment]
I had the same issue, I used bootstrap with this grid, and found that safari doesn't work correct with bootstrap 'clearfix' on .row, 'clearfix' uses 'display:table;', and for safari it's more important than 'display:flex;', I don't know why.

**Comment by kristoferjoseph** [comment]
looks like this was fixed in 6.3.1
Please give it a whirl

**Comment by bruceCzK** [comment]
Is 6.3.1 released yet? Not receiving update in bower. @kristoferjoseph 
```
Additional error details:
Available versions in https://github.com/kristoferjoseph/flexboxgrid.git: 6.3.0, 6.2.0, 6.1.1, 6.1.0, 6.0.0, 5.0.0, 4.0.0, 3.0.1, 3.0.0, 2.0.0, 1.1.1, 1.1.0, 1.0.0, 0.2.0, 0.1.1, 0.1.0
```

**Comment by kristoferjoseph** [comment]
I am sorry I can't help more, I do not use bower personally and have no idea what it needs to be happy. Feel free to make a PR if you figure it out and let me know what the issue was. Thanks!

**Comment by brad-decker** [comment]
Still having issues with flexbox grid in older versions of safari and chrome that use webkit prefixes. We utilize flexboxgrid via react-flexbox-grid module. Any insight into what is going on would be appreciated.
