### ISSUE TITLE
horizontal scrolling

### ISSUE THREAD

**Issue by slavikse** [kristoferjoseph/flexboxgrid#144]
By reducing the width of the screen: 780px 1030 px 1220 px appears horizontal scrolling.
When using normalize.css to a width of 800px there is a constant horizontal scrolling.
code:
<div class="container">
  <div class="row">
    <div class="col-xs-4">txt</div>
    <div class="col-xs-4">txt</div>
    <div class="col-xs-4">txt</div>
  </div>
</div>

**Comment by kristoferjoseph** [comment]
Thanks, `container` needs to be fixed. `container-fluid` should work. Are you needing static sizes?

**Comment by ArnaudValensi** [comment]
I have the same issue. Even using only a `row` without a `container`.

**Comment by nicolasartman** [comment]
Yep, both container classes seem to have their calculations slightly off so there's a horizontal scroll for at least 30px at each responsive breakpoint. Checked this using a barebones page like the code above and the CDN link to v6.3.0.

**Comment by philippotto** [comment]
Any updates on this one?

**Comment by kristianwithak** [comment]
For what it's worth, I can also confirm having horizontal scrolling on mobile with the use of `.col-xs-12`... also, I'm using only a containing `.row`, no `.container`, `.container-fluid`, or `.wrap` classes anywhere.

The `.row` class is applying the `-1em` margins, which widens the div beyond the left/right edges of the viewport, and the subsequent `.col-[xx]` columns have their padding of `1em`.

Lookin' forward to any info on a fix, thanks!

**Comment by stephantabor** [comment]
Also experiencing this issue. For whatever reason my widths are off by `1em` so i added a max width to the `.container` class and it solved my issue.

```scss
.container {
    max-width: calc(100% - 1em);
}
```

**Comment by kristoferjoseph** [comment]
Yeah, I have been experimenting with this a lot and have decided to use a different approach since a lot of people have run into issues. Will publish soon.

**Comment by juniovitorino** [comment]
Some update about this? Very simple things are affected now. :(

**Comment by manuelmazzuola** [comment]
I have the same issue.
I've discovered that removing the negatives margins on the row class fixes the issue.

**Comment by helvanic** [comment]
Is there any update on this matter? Changing the margins causes some weird behaviors. This needs to work.

**Comment by kristoferjoseph** [comment]
This is a very common issue that has been talked to a bunch in previous closed issues.

I have been working on a fix that does not require the margin hack, but just so we are all clear the margin hack is needed for when you rely on `flex-wrap` to wrap row contents ( see flexboxgrid.com for an example ). 

This was refactored by a PR to match the bootstrap-grid api which requires container as well as some normalizing or reset styling to work like bootstrap does.

[I use a simple yet heavy handed reset](https://github.com/kristoferjoseph/dam-reset/blob/master/style.css) which is probably why I have never had this issue. 

You could also include whatever reset boostrap is using in the meantime.

**Comment by or2008** [comment]
for me adding: 
  padding-left: 15px;
  padding-right: 15px;

to .container fixed the problem.

I saw bootstrap 4 is using it in their flexbox grid, why won't you?

**Comment by nbonnefoy** [comment]
Fixed using a wrapper :
`.container {
	padding: 1rem;
}`
Then the structure should be :
container
    row
        column

**Comment by DanielRamosAcosta** [comment]
Is there any updates on this?

**Comment by necrodevz** [comment]
Is there any update on this?

**Comment by SuEric** [comment]
abandoned?

**Comment by lfender6445** [comment]
@kristoferjoseph you mentioned a possible fix? 

using your reset.css approach i still have the issue 

![x](http://g.recordit.co/Tu6jAahlpS.gif)

**Comment by lfender6445** [comment]
@stephantabor your solution gets me the closest

**Comment by evgenyrodionov** [comment]
Fixed in forked [flexboxgrid2](https://github.com/evgenyrodionov/flexboxgrid2).

**Comment by sazad2** [comment]
@evgenyrodionov mind opening a PR here?

**Comment by evgenyrodionov** [comment]
@sazad2 this project looks abandoned, so I decided to fork it. Switch to flexboxgrid2.

**Comment by ronnymedinave** [comment]
I have this problem when normalize.css has been added, it exists
 a solution?

**Comment by ahmedghazi** [comment]
On mobile if you don't need gutter simply a
`
.row{
      margin: 0;
    }
    [class^="col-"],
    [class*=" col-"]{
        padding: 0;
    }
`
